package cn.calculator;

import com.google.gson.JsonObject;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

/** Verifies durable storage and durable single-record deletion across database reopening. */
public final class HistoryRepositoryTest {
  private static int checks;
  public static void main(String[] args) throws Exception {
    Path testDirectory = Files.createTempDirectory("calculator-history-test-");
    Path database = testDirectory.resolve("history");
    long firstId;
    long secondId;
    try {
      try (HistoryRepository repository = new HistoryRepository(database.toString())) {
        check(repository.isHealthy(), "Database health");
        check(repository.findAll().isEmpty(), "Database starts empty");
        firstId = repository.save("0.1 + 0.2", "0.3").id;
        secondId = repository.save("(1 + 2) * 3", "9").id;
        check(secondId > firstId, "Unique increasing IDs");
      }
      try (HistoryRepository reopened = new HistoryRepository(database.toString())) {
        List<CalculationRecord> records = reopened.findAll();
        check(records.size() == 2, "Both records survive reopening");
        check(records.get(0).id == secondId, "Newest first");
        check("0.3".equals(records.get(1).result), "Decimal result remains exact");
        check(records.get(1).createdAt.endsWith("Z"), "UTC timestamp");
        check(reopened.delete(firstId), "Deletes requested record");
        check(!reopened.delete(firstId), "Missing record is detected");
      }
      try (HistoryRepository reopened = new HistoryRepository(database.toString())) {
        List<CalculationRecord> records = reopened.findAll();
        check(records.size() == 1 && records.get(0).id == secondId,
            "Deletion survives reopening and preserves other record");
        JsonObject parameters = new JsonObject();
        parameters.addProperty("value", "ff");
        parameters.addProperty("fromBase", 16);
        parameters.addProperty("toBase", 10);
        reopened.save("FF (base 16) to base 10", "255", "base", parameters);
      }
      try (HistoryRepository reopened = new HistoryRepository(database.toString())) {
        CalculationRecord converted = reopened.findAll().get(0);
        check("base".equals(converted.type), "Operation type survives reopening");
        check("ff".equals(converted.parameters.get("value").getAsString()),
            "Original input survives reopening");
        check(converted.parameters.get("fromBase").getAsInt() == 16,
            "Numeric parameters survive reopening");
        check("255".equals(converted.result), "Converted result survives reopening");
      }
      try (HistoryRepository reopened = new HistoryRepository(database.toString())) {
        check(reopened.deleteAll() == 2, "Clear all removes calculation and legacy records");
        check(reopened.deleteAll() == 0, "Clearing empty history is idempotent");
      }
      try (HistoryRepository reopened = new HistoryRepository(database.toString())) {
        check(reopened.findAll().isEmpty(), "Clear all survives reopening");
        check(reopened.save("2+2", "4").id > secondId, "Saving works after clear all");
      }
      migration(testDirectory.resolve("legacy"));
      System.out.println("PASS: " + checks + " database checks");
    } finally {
      Files.deleteIfExists(testDirectory.resolve("history.mv.db"));
      Files.deleteIfExists(testDirectory.resolve("history.trace.db"));
      Files.deleteIfExists(testDirectory.resolve("legacy.mv.db"));
      Files.deleteIfExists(testDirectory.resolve("legacy.trace.db"));
      Files.deleteIfExists(testDirectory);
    }
  }

  private static void check(boolean value, String message) {
    if (!value) {
      throw new AssertionError(message);
    }
    checks++;
  }

  private static void migration(Path database) throws Exception {
    String url = "jdbc:h2:file:" + database.toString().replace('\\', '/') + ";WRITE_DELAY=0";
    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement()) {
      statement.execute("CREATE TABLE calculation_history ("
          + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
          + "expression VARCHAR(512) NOT NULL, result VARCHAR(1000) NOT NULL, "
          + "created_at VARCHAR(40) NOT NULL)");
      try (PreparedStatement insert = connection.prepareStatement(
          "INSERT INTO calculation_history(expression, result, created_at) VALUES (?, ?, ?)")) {
        insert.setString(1, "1 + 2");
        insert.setString(2, "3");
        insert.setString(3, "2026-10-01T04:00:00Z");
        insert.executeUpdate();
      }
    }
    try (HistoryRepository migrated = new HistoryRepository(database.toString())) {
      List<CalculationRecord> records = migrated.findAll();
      check(records.size() == 1, "Migration preserves legacy record count");
      CalculationRecord record = records.get(0);
      check(record.id == 1 && "3".equals(record.result), "Migration preserves IDs and results");
      check("2026-10-01T04:00:00Z".equals(record.createdAt), "Migration preserves timestamps");
      check("calculation".equals(record.type), "Legacy records receive the calculation type");
      check("1 + 2".equals(record.parameters.get("expression").getAsString()),
          "Legacy records receive reusable expressions");
      check("deg".equals(record.parameters.get("angleMode").getAsString()),
          "Legacy records default to degree mode");
    }
    try (HistoryRepository migratedAgain = new HistoryRepository(database.toString())) {
      check(migratedAgain.findAll().size() == 1, "Migration is repeatable without duplicating records");
      check(migratedAgain.save("2 + 2", "4").id == 2, "Migrated identity continues increasing");
    }
  }
}
