package cn.calculator;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/** Local H2 or remote PostgreSQL persistence. Mutations commit before returning. */
public final class HistoryRepository implements AutoCloseable {
  private final String databaseUrl;
  private final String databaseUser;
  private final String databasePassword;
  private final Connection keeper;

  public HistoryRepository(String databasePath) throws SQLException, IOException {
    this(databasePath, null, null, null);
  }

  public HistoryRepository(String databasePath, String jdbcUrl, String user, String password)
      throws SQLException, IOException {
    boolean remote = jdbcUrl != null && !jdbcUrl.trim().isEmpty();
    if (remote) {
      if (!jdbcUrl.startsWith("jdbc:postgresql://")) {
        throw new IllegalArgumentException("DATABASE_URL must be a PostgreSQL JDBC URL.");
      }
      databaseUrl = jdbcUrl;
      databaseUser = user;
      databasePassword = password;
    } else {
      if (databasePath.indexOf(';') >= 0) {
        throw new IllegalArgumentException("DB_PATH must not contain a semicolon.");
      }
      Path path = Paths.get(databasePath).toAbsolutePath().normalize();
      Files.createDirectories(path.getParent());
      databaseUrl = "jdbc:h2:file:" + path.toString().replace('\\', '/')
          + ";DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0";
      databaseUser = "sa";
      databasePassword = "";
    }
    keeper = remote ? null : open();
    Connection initialization = remote ? open() : keeper;
    try (Statement statement = initialization.createStatement()) {
      statement.execute("CREATE TABLE IF NOT EXISTS calculation_history ("
          + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
          + "expression VARCHAR(512) NOT NULL, "
          + "result VARCHAR(1000) NOT NULL, "
          + "created_at VARCHAR(40) NOT NULL, "
          + "record_type VARCHAR(20) DEFAULT 'calculation' NOT NULL, "
          + "parameters VARCHAR(4096))");
      statement.execute("ALTER TABLE calculation_history ADD COLUMN IF NOT EXISTS "
          + "record_type VARCHAR(20) DEFAULT 'calculation' NOT NULL");
      statement.execute("ALTER TABLE calculation_history ADD COLUMN IF NOT EXISTS "
          + "parameters VARCHAR(4096)");
      migrateLegacyParameters(initialization);
    } catch (SQLException exception) {
      if (keeper != null) keeper.close();
      throw exception;
    } finally {
      if (remote) initialization.close();
    }
  }

  public CalculationRecord save(String expression, String result) throws SQLException {
    return save(expression, result, "calculation", CalculationRecord.defaultParameters(expression));
  }

  public CalculationRecord save(String expression, String result, String type, JsonObject parameters)
      throws SQLException {
    String createdAt = Instant.now().toString();
    String sql = "INSERT INTO calculation_history "
        + "(expression, result, created_at, record_type, parameters) VALUES (?, ?, ?, ?, ?)";
    try (Connection connection = open();
        PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
      statement.setString(1, expression);
      statement.setString(2, result);
      statement.setString(3, createdAt);
      statement.setString(4, type);
      statement.setString(5, parameters.toString());
      statement.executeUpdate();
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (!keys.next()) {
          throw new SQLException("No generated history ID");
        }
        return new CalculationRecord(keys.getLong(1), expression, result, createdAt, type, parameters);
      }
    }
  }

  public List<CalculationRecord> findAll() throws SQLException {
    List<CalculationRecord> records = new ArrayList<>();
    String sql = "SELECT id, expression, result, created_at, record_type, parameters "
        + "FROM calculation_history ORDER BY id DESC";
    try (Connection connection = open();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {
      while (resultSet.next()) {
        records.add(new CalculationRecord(resultSet.getLong("id"), resultSet.getString("expression"),
            resultSet.getString("result"), resultSet.getString("created_at"),
            resultSet.getString("record_type"),
            JsonParser.parseString(resultSet.getString("parameters")).getAsJsonObject()));
      }
    }
    return records;
  }

  public int deleteAll() throws SQLException {
    try (Connection connection = open();
        PreparedStatement statement = connection.prepareStatement("DELETE FROM calculation_history")) {
      return statement.executeUpdate();
    }
  }

  public boolean delete(long id) throws SQLException {
    try (Connection connection = open();
        PreparedStatement statement = connection.prepareStatement(
            "DELETE FROM calculation_history WHERE id = ?")) {
      statement.setLong(1, id);
      return statement.executeUpdate() == 1;
    }
  }

  public boolean isHealthy() throws SQLException {
    try (Connection connection = open();
        PreparedStatement statement = connection.prepareStatement("SELECT 1");
        ResultSet resultSet = statement.executeQuery()) {
      return resultSet.next() && resultSet.getInt(1) == 1;
    }
  }

  private Connection open() throws SQLException {
    if (databaseUser == null) return DriverManager.getConnection(databaseUrl);
    return DriverManager.getConnection(databaseUrl, databaseUser, databasePassword);
  }

  private void migrateLegacyParameters(Connection connection) throws SQLException {
    try (PreparedStatement select = connection.prepareStatement(
        "SELECT id, expression FROM calculation_history WHERE parameters IS NULL");
        ResultSet records = select.executeQuery();
        PreparedStatement update = connection.prepareStatement(
            "UPDATE calculation_history SET parameters = ? WHERE id = ?")) {
      while (records.next()) {
        update.setString(1, CalculationRecord.defaultParameters(
            records.getString("expression")).toString());
        update.setLong(2, records.getLong("id"));
        update.executeUpdate();
      }
    }
  }

  @Override
  public void close() throws SQLException {
    if (keeper != null) keeper.close();
  }
}
